name: hyperfine
version: git
summary: "A command-line benchmarking tool"
description: |
  A command-line benchmarking tool (inspired by bench). 
  Features
    * Statistical analysis across multiple runs.
    * Support for arbitrary shell commands.
    * Constant feedback about the benchmark progress and current estimates.
    * Warmup runs can be executed before the actual benchmark.
    * Cache-clearing commands can be set up before each timing run.
    * Statistical outlier detection.
    * Export results to various formats: CSV, JSON, Markdown.
    * Parameterized benchmarks.
    * Cross-platform

grade: stable
confinement: classic

parts:
  hyperfine:
    plugin: rust
    source: ./

apps:
  hyperfine:
    command: bin/hyperfine
